apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    {{- include "postgres-database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    {{- include "postgres-database.selectorLabels" . | nindent 4 }}
